### PR TITLE
chore: add sitemap

### PR DESCRIPTION
**Pull request by donmckenna**
Add `sitemap.xml` functionality, and update `vitepress`
- Vitepress update broke a lot of styles and some config. This was fixed in both [WC Docs](https://github.com/stackblitz/webcontainer-docs/pull/45) and these docs.

Closes MKT-57

`lastmod` proof:

Screen Shot 2023-10-15 at 4 10 05 PM

### CODE REVIEW

**Review by sulco — COMMENTED** [review]
Were you able to get `lastmod` into the sitemap somehow?

As [per VitePress docs](https://vitepress.dev/reference/default-theme-last-updated), I've tried modifying the file (and even comitting it just in case) and then running the build, but the sitemap still doesn't have the `lastmod`

**Comment by donmckenna** [comment]
Yeah it seemed to work for me. 
I had to `npm run build` and the updated sitemap with `lastmod` shows up in the `build` directory.

**Comment by donmckenna** [comment]
@sulco Also the Vitepress update broke some styles. Worked on them yesterday, but finishing today.

**Review by sulco — APPROVED** [review]
lgtm, thanks man!

**Pull request merged**
