### PR TITLE
fix: remove background color transitions from dark/light switch 

### PR DESCRIPTION
**Pull request by kevinzunigacuellar**
# PR Description

This PR fixes the issue number:  #52 

### Summary of my changes and explanation of my decisions

- remove `background-color` transitions

### Self-check

Please check all that apply:

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my code or content update and edited it to the best of my abilities
- [x] I have commented my code, particularly in hard-to-understand areas; my comments are concise

### Contributors list

Would you like your contribution to be celebrated? Please check all that apply: 

(~idk 😅) I was testing out codeflow 

- [ ] I would like to be featured on the future contributors list in the README. If so, please tell us:
  - what name you'd like to be shown there?
  - we usually link github profile pic -- is that ok? If not, provide another url: 
  - we usually link your github profile but if you have a portfolio page, provide a link:

- [ ] I would like to get a shoutout in the next monthly updates post. If so, please provide your twitter handle (or we will link to your GitHub profile).

⚡️ ⚡️ ⚡️  Thank you for contributing to StackBlitz ⚡️ ⚡️ ⚡️

### CODE REVIEW

**Comment by fvsch** [comment]
I'd prefer if we could address the issue upstream in Vitepress.

**Comment by fvsch** [comment]
Tried it in the preview deploy, and it does feel like a small improvement.

Given that it's not a big fix, I think it would be okay to have this in our `fixes.scss` styles.

@sylwiavargas what do you think?

**Comment by sylwiavargas** [comment]
Hi @kevinzunigacuellar! Thank you for the contribution - and for being the first external contributor to make a PR using Codeflow! 💙
@fvsch - I'd say we could do both! Merge this fix and address the issue upstream with VitePress. 

@kevinzunigacuellar would you like to raise an issue with VitePress (we are using VitePress default theme)? We can do that as well but since this is your "find", wanted to ask you :)

**Review by sylwiavargas — APPROVED** [review]

**Comment by kevinzunigacuellar** [comment]
hello @sylwiavargas thank you for accepting my PR 🚀. I can raise an issue to VitePress and link the issue here to track its progress.

I wanted to try codeflow and it was very smooth (love it 🦄). I will start using it all the time btw. I don't know if the offer of joining the contributor list is still open but if it is I would love to be part of it. Once again thank you and @fvsch for taking the time to review my PR. Have a nice day

**Comment by kevinzunigacuellar** [comment]
vuejs/vitepress#1479 got merged 🥳

**Pull request merged**
